<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class BookSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $books = [
            [
                'thumbnail' => 'Cover54.webp',
                'title' => 'Neural Networks Math: A Visual Introduction for Beginners',
                'author' => 'Michael Taylor',
                'description' => 'Taylor\'s book offers a visual approach to understanding the mathematics behind neural networks. It breaks down complex mathematical concepts into easily digestible sections, using diagrams and illustrations to enhance comprehension. This beginner-friendly guide is designed for individuals new to the field of machine learning who want to grasp the mathematical foundations necessary for working with neural networks.',
                'category_id' => 4,
                'publish_date' => '2021-04-22',
                'book_path' => 'Book54.pdf',
            ],
            [
                'thumbnail' => 'Cover1.webp',
                'title' => 'Discrete Mathematics with Applications Edition: 3',
                'author' => 'Susanna S.Epp',
                'description' => 'This textbook provides an in-depth exploration of discrete mathematics, emphasizing its applications in computer science and related fields. Epp presents key concepts such as logic, set theory, combinatorics, graph theory, and algorithms in a clear and engaging manner. The book is designed to develop students\' problem-solving skills through numerous examples and exercises, making it an essential resource for those pursuing studies in mathematics or computer science.',
                'category_id' => 1,
                'publish_date' => '2018-01-10',
                'book_path' => 'Book1.pdf',
            ],
            [
                'thumbnail' => 'Cover57.webp',
                'title' => 'Natural Language Processing with PyTorch',
                'author' => 'Delip Rao, Brian McMahan',
                'description' => 'From the Preface This book aims to bring newcomers to natural language processing (NLP) and deep learning to a tasting table covering important topics in both areas. Both of these subject areas are growing exponentially. As it introduces both deep learning and NLP with an emphasis on implementation, this book occupies an important middle ground. While writing the book, we had to make difficult, and sometimes uncomfortable, choices on what material to leave out. For a beginner reader, we hope the book will provide a strong foundation in the basics and a glimpse of what is possible. Machine learning, and deep learning in particular, is an experiential discipline, as opposed to an intellectual science. The generous end-to-end code examples in each chapter invite you to partake in that experience. A note regarding the style of the book. We have intentionally avoided mathematics in most places, not because deep learning math is particularly difficult (it is not), but because [...]it is a distraction in many situations from the main goal of this book—to empower the beginner learner. Likewise, in many cases, both in code and text, we have favored exposition over succinctness. Advanced readers and experienced programmers will likely see ways to tighten up the code and so on, but our choice was to be as explicit as possible so as to reach the broadest of the audience that we want to reach.',
                'category_id' => 4,
                'publish_date' => '2019-07-11',
                'book_path' => 'Book57.pdf',
            ],
            [
                'thumbnail' => 'Cover47.webp',
                'title' => 'Deep Learning: Foundations and Concepts',
                'author' => 'Christopher M. Bishop, Hugh Bishop',
                'description' => 'Bishop et al provide comprehensive coverage regarding foundational theories behind deep learning methodologies discussing core principles alongside practical applications relevant across various domains where intelligent solutions increasingly sought after today overall ensuring thorough understanding overall throughout process itself itself!',
                'category_id' => 4,
                'publish_date' => '2018-09-19',
                'book_path' => 'Book47.pdf',
            ],
            [
                'thumbnail' => 'Cover29.webp',
                'title' => 'Artificial Intelligence: A Guide to Intelligent Systems',
                'author' => 'Michael Negnevitsky',
                'description' => 'Negnevitsky presents an accessible overview covering key concepts related directly towards intelligent systems—including machine learning methodologies & decision-making processes—providing valuable insights applicable across various domains where intelligent solutions are increasingly sought after today!',
                'category_id' => 2,
                'publish_date' => '2017-01-19',
                'book_path' => 'Book29.pdf',
            ],
            [
                'thumbnail' => 'Cover41.webp',
                'title' => 'Introduction To Algo Trading: How Retail Traders Can Successfully Compete With Professional Traders',
                'author' => 'Kevin J. Davey',
                'description' => 'Davey shares insights aimed directly at retail traders looking compete against professionals within financial markets; discussing strategies employed successful traders along best practices ensuring profitability amidst increasing competition today!',
                'category_id' => 3,
                'publish_date' => '2018-07-18',
                'book_path' => 'Book41.pdf',
            ],
            [
                'thumbnail' => 'Cover2.webp',
                'title' => 'Algorithms in C, Parts 1-4: Fundamentals, Data Structures, Sorting, Searching Edition: 3',
                'author' => 'Robert Sedgewick',
                'description' => 'Sedgewick\'s comprehensive guide covers fundamental algorithms and data structures using the C programming language. The book is divided into four parts: fundamentals, data structures, sorting, and searching. Each section provides clear explanations and illustrative examples to help readers understand complex concepts. This resource is ideal for computer science students and practitioners looking to deepen their understanding of algorithm design and analysis.',
                'category_id' => 1,
                'publish_date' => '1998-02-23',
                'book_path' => 'Book2.pdf',
            ],
            [
                'thumbnail' => 'Cover3.webp',
                'title' => 'Programming Logic and Design, Introductory Edition: 9',
                'author' => 'Joyce Farrell',
                'description' => 'Farrell\'s text introduces the principles of programming logic and design with a focus on structured programming techniques. The book emphasizes problem-solving skills and logical thinking through a variety of examples and exercises. It is suitable for beginners in programming, providing a solid foundation for further study in various programming languages.',
                'category_id' => 1,
                'publish_date' => '2020-03-13',
                'book_path' => 'Book3.pdf',
            ],
            [
                'thumbnail' => 'Cover4.webp',
                'title' => 'Programming Language Concepts Edition: 2nd',
                'author' => 'Peter Sestoft',
                'description' => 'This book offers a thorough examination of programming language concepts, including syntax, semantics, and implementation techniques. Sestoft discusses various programming paradigms and provides insights into language design and the principles that underlie modern programming languages. It serves as a valuable resource for students interested in understanding the theoretical aspects of programming languages.',
                'category_id' => 1,
                'publish_date' => '2019-08-24',
                'book_path' => 'Book4.pdf',
            ],
            [
                'thumbnail' => 'Cover5.webp',
                'title' => 'Hacking APIs: Breaking Web Application Programming Interfaces',
                'author' => 'Corey J. Ball',
                'description' => 'In this practical guide, Ball explores the vulnerabilities associated with web application programming interfaces (APIs). The book provides insights into common security flaws and demonstrates techniques for ethical hacking to identify and mitigate these risks. It is an essential resource for security professionals looking to enhance their understanding of API security.',
                'category_id' => 1,
                'publish_date' => '2020-02-21',
                'book_path' => 'Book5.pdf',
            ],
            [
                'thumbnail' => 'Cover6.webp',
                'title' => 'Discrete Mathematics and Functional Programming',
                'author' => 'Thomas VanDrunen',
                'description' => 'VanDrunen\'s text integrates discrete mathematics with functional programming concepts, providing a unique approach to both subjects. The book emphasizes the importance of mathematical reasoning in computer science while introducing functional programming techniques through practical examples. This resource is ideal for students seeking to understand the connections between mathematics and computer programming.',
                'category_id' => 1,
                'publish_date' => '2011-02-23',
                'book_path' => 'Book6.pdf',
            ],
            [
                'thumbnail' => 'Cover7.webp',
                'title' => 'Data Structures and C Programs',
                'author' => 'Christopher J. Van Wyk',
                'description' => 'This textbook focuses on essential data structures and their implementation in C programming. Van Wyk covers various data structures such as arrays, linked lists, stacks, queues, trees, and graphs while emphasizing algorithmic efficiency. The book includes numerous examples and exercises that reinforce understanding and provide practical coding experience.',
                'category_id' => 1,
                'publish_date' => '1999-03-13',
                'book_path' => 'Book7.pdf',
            ],
            [
                'thumbnail' => 'Cover8.webp',
                'title' => 'The Rust Programming Language, 2nd Edition',
                'author' => 'Steve Klabnik, Carol Nichols',
                'description' => 'Klabnik and Nichols present a comprehensive guide to the Rust programming language, known for its performance and safety features. The book covers Rust\'s syntax, core concepts, ownership model, concurrency features, and best practices for building reliable software. It serves as both an introduction for beginners and a reference for experienced developers looking to adopt Rust',
                'category_id' => 1,
                'publish_date' => '2018-02-17',
                'book_path' => 'Book8.pdf',
            ],
            [
                'thumbnail' => 'Cover9.webp',
                'title' => 'Algorithmic Thinking: A Problem-Based Introduction',
                'author' => 'Daniel Zingaro',
                'description' => 'Zingaro\'s book promotes algorithmic thinking through problem-solving techniques applicable to various computational challenges. The text emphasizes the importance of understanding algorithms as a means to develop effective solutions to problems. With engaging examples and exercises, this resource is suitable for students learning computer science concepts.',
                'category_id' => 1,
                'publish_date' => '2016-01-15',
                'book_path' => 'Book9.pdf',
            ],
            [
                'thumbnail' => 'Cover10.webp',
                'title' => 'Competitive Programming in Python: 128 Algorithms to Develop your Coding Skills',
                'author' => 'Christoph Dürr, Jill-Jênn Vie',
                'description' => 'This book provides a collection of 128 algorithms specifically designed to enhance coding skills for competitive programming using Python. Dürr and Vie cover a wide range of topics including graph algorithms, dynamic programming, geometry, and number theory. Each algorithm is explained with clear examples that help readers understand its application in competitive scenarios.',
                'category_id' => 1,
                'publish_date' => '2020-02-16',
                'book_path' => 'Book10.pdf',
            ],
            [
                'thumbnail' => 'Cover11.webp',
                'title' => 'Data Structures and Algorithm Analysis in Java, 3rd Edition',
                'author' => 'Mark Allen Weiss',
                'description' => 'Weiss\'s text offers an extensive examination of data structures and algorithm analysis using Java as the primary language. The book covers fundamental concepts such as arrays, linked lists, trees, graphs, sorting algorithms, and complexity analysis. With numerous examples and exercises throughout the text, this resource is ideal for students seeking to master data structures in Java.',
                'category_id' => 1,
                'publish_date' => '2013-02-19',
                'book_path' => 'Book11.pdf',
            ],
            [
                'thumbnail' => 'Cover12.webp',
                'title' => 'Python for data analysis',
                'author' => 'Wes McKinney',
                'description' => 'McKinney\'s book serves as a practical guide to data analysis using Python\'s powerful pandas library. The text covers essential techniques for data manipulation, cleaning, visualization, and analysis with real-world examples drawn from various domains. This resource is invaluable for data scientists looking to leverage Python for effective data analysis.',
                'category_id' => 1,
                'publish_date' => '2018-12-13',
                'book_path' => 'Book12.pdf',
            ],
            [
                'thumbnail' => 'Cover13.webp',
                'title' => 'Python Programming for Beginners',
                'author' => 'Evergreen Press',
                'description' => 'This introductory guide teaches the fundamentals of Python programming through clear explanations and hands-on exercises. Designed specifically for beginners, the book covers basic syntax, control structures, functions, file handling, and more. It provides an accessible entry point into the world of programming with Python.',
                'category_id' => 1,
                'publish_date' => '2020-04-12',
                'book_path' => 'Book13.pdf',
            ],
            [
                'thumbnail' => 'Cover14.webp',
                'title' => 'Java: The Complete Reference, Twelfth Edition',
                'author' => 'Herbert Schildt',
                'description' => 'Schildt\'s comprehensive reference covers all aspects of Java programming from basic syntax to advanced features like JavaFX and concurrency models. This updated edition includes new features introduced in recent versions of Java while providing clear explanations supported by practical examples. It serves as both an introduction for beginners and a reference for experienced programmers.',
                'category_id' => 1,
                'publish_date' => '2019-06-17',
                'book_path' => 'Book14.pdf',
            ],
            [
                'thumbnail' => 'Cover15.webp',
                'title' => 'Data Structure and Algorithm',
                'author' => 'Nikhat Raza Khan, Manmohan Singh, Piyush Kumar',
                'description' => 'This textbook provides an overview of essential data structures and algorithms necessary for computer science students. The authors cover topics such as arrays, linked lists, stacks, queues, trees, graphs, sorting algorithms, and searching techniques with practical examples that facilitate understanding of these fundamental concepts.',
                'category_id' => 1,
                'publish_date' => '2021-03-14',
                'book_path' => 'Book15.pdf',
            ],
            [
                'thumbnail' => 'Cover16.webp',
                'title' => 'The Cambridge Handbook of Artificial Intelligence: Global Perspectives on Law and Ethics',
                'author' => 'Larry A. DiMatteo (editor), Cristina Poncibò (editor), Michel Cannarsa (editor)',
                'description' => 'This handbook explores the multifaceted implications of artificial intelligence on law and ethics from global perspectives. Edited by leading experts in the field, it discusses regulatory frameworks, ethical considerations surrounding AI technologies, privacy issues, accountability measures, and the impact on society at large—making it an essential resource for policymakers and practitioners alike.',
                'category_id' => 2,
                'publish_date' => '2020-06-17',
                'book_path' => 'Book16.pdf',
            ],
            [
                'thumbnail' => 'Cover25.webp',
                'title' => 'The Complete Obsolete Guide to Generative AI',
                'author' => 'David Clinton',
                'description' => 'Clinton\'s guide offers an overview of generative AI technologies—their applications across industries & challenges they present—while emphasizing ethical considerations surrounding their use; serving as a critical resource amidst growing concerns regarding responsible deployment within society today.',
                'category_id' => 2,
                'publish_date' => '2023-04-14',
                'book_path' => 'Book25.pdf',
            ],
            [
                'thumbnail' => 'Cover17.webp',
                'title' => 'AI Needs You',
                'author' => 'Verity Harding',
                'description' => 'Harding\'s book addresses the critical role humans play in shaping artificial intelligence technologies while exploring ethical considerations surrounding AI development. Through engaging narratives and case studies, it emphasizes collaboration between humans and AI systems to ensure responsible innovation that benefits society.',
                'category_id' => 2,
                'publish_date' => '2021-09-18',
                'book_path' => 'Book17.pdf',
            ],
            [
                'thumbnail' => 'Cover18.webp',
                'title' => 'Artificial Intelligence: A Modern Approach Edition: 3rd',
                'author' => 'Stuart Russell, Peter Norvig',
                'description' => 'Russell and Norvig present a foundational text on artificial intelligence that covers a wide range of topics including machine learning algorithms, reasoning systems, robotics applications, natural language processing (NLP), ethics in AI development among others—making it an indispensable resource for students aspiring to understand AI comprehensively.',
                'category_id' => 2,
                'publish_date' => '2010-11-10',
                'book_path' => 'Book18.pdf',
            ],
            [
                'thumbnail' => 'Cover19.webp',
                'title' => 'ChatGPT for Coders Unlock the Power of AI with ChatGPT: A Comprehensive Guide to Efficient and Effective Coding',
                'author' => 'Sean A. Williams',
                'description' => 'Williams\' guide introduces coders to utilizing ChatGPT effectively within their coding practices—offering tips on how to leverage AI-generated suggestions while maintaining code quality standards across various programming tasks—thus enhancing productivity without compromising creativity or accuracy.',
                'category_id' => 2,
                'publish_date' => '2023-11-15',
                'book_path' => 'Book19.pdf',
            ],
            [
                'thumbnail' => 'Cover20.webp',
                'title' => 'Artificial Intelligence A-Z: Learn How To Build An AI',
                'author' => 'Nileriver Publications',
                'description' => 'This comprehensive guide teaches readers how to build their own artificial intelligence applications from scratch—covering foundational concepts alongside practical implementation steps across different domains—making it suitable even for those new to AI development.',
                'category_id' => 2,
                'publish_date' => '2020-02-10',
                'book_path' => 'Book20.pdf',
            ],
            [
                'thumbnail' => 'Cover21.webp',
                'title' => 'Pythonic AI: A beginner\'s guide to building AI applications in Python',
                'author' => 'Arindam Banerjee',
                'description' => 'Banerjee\'s beginner-friendly text introduces readers to building artificial intelligence applications using Python—a popular language among developers—by breaking down complex concepts into manageable sections with hands-on projects that reinforce learning through practice.',
                'category_id' => 2,
                'publish_date' => '2021-06-17',
                'book_path' => 'Book21.pdf',
            ],
            [
                'thumbnail' => 'Cover22.webp',
                'title' => 'Application of AI in Credit Scoring Modeling',
                'author' => 'Bohdan Popovych',
                'description' => 'Popovych explores how artificial intelligence can be applied effectively within credit scoring models—discussing methodologies used to enhance predictive accuracy while addressing challenges faced during implementation—making it relevant reading material for finance professionals interested in leveraging AI technologies.',
                'category_id' => 2,
                'publish_date' => '2022-07-14',
                'book_path' => 'Book22.pdf',
            ],
            [
                'thumbnail' => 'Cover23.webp',
                'title' => 'Artificial Intelligence for Business',
                'author' => 'Rajendra Akerkar',
                'description' => 'Akerkar\'s book discusses how businesses can harness artificial intelligence technologies effectively—providing insights into strategic implementations across various sectors—from improving operational efficiency to enhancing customer experiences—thus serving as a valuable resource for business leaders looking towards innovation through technology adoption.',
                'category_id' => 2,
                'publish_date' => '2021-08-30',
                'book_path' => 'Book23.pdf',
            ],
            [
                'thumbnail' => 'Cover24.webp',
                'title' => 'AI Love You',
                'author' => 'Yuefang Zhou, Martin H. Fischer',
                'description' => 'This thought-provoking exploration delves into the intersection between artificial intelligence technology advancements & human relationships—discussing ethical implications surrounding emotional connections formed between humans & machines while examining future possibilities that arise from such interactions.',
                'category_id' => 2,
                'publish_date' => '2021-02-12',
                'book_path' => 'Book24.pdf',
            ],
            [
                'thumbnail' => 'Cover26.webp',
                'title' => 'Artificial Intelligence for Robotics',
                'author' => 'Francis X. Govers',
                'description' => 'Govers focuses on integrating artificial intelligence techniques within robotics systems; discussing algorithms & frameworks enabling intelligent behavior—making this text essential reading material not only for robotics enthusiasts but also researchers exploring innovative solutions utilizing these technologies together effectively!',
                'category_id' => 2,
                'publish_date' => '2020-06-15',
                'book_path' => 'Book26.pdf',
            ],
            [
                'thumbnail' => 'Cover27.webp',
                'title' => 'You Look Like a Thing and I Love You',
                'author' => 'Janelle Shane',
                'description' => 'Shane\'s humorous take on artificial intelligence explores its quirks & limitations through engaging anecdotes; providing insights into how AI systems function while highlighting potential pitfalls associated with relying too heavily upon them—ultimately encouraging readers towards critical thinking about technology\'s role within society today!',
                'category_id' => 2,
                'publish_date' => '2019-09-10',
                'book_path' => 'Book27.pdf',
            ],
            [
                'thumbnail' => 'Cover28.webp',
                'title' => 'Zero to AI',
                'author' => 'Nicolo Valigi, Gianluca Mauro',
                'description' => 'Valigi & Mauro provide readers with step-by-step guidance on learning artificial intelligence—from foundational principles through practical implementations; making this accessible introduction suitable even if starting from scratch without prior experience; thus empowering individuals interested in entering this rapidly evolving field!',
                'category_id' => 2,
                'publish_date' => '2022-12-15',
                'book_path' => 'Book28.pdf',
            ],

            [
                'thumbnail' => 'Cover30.webp',
                'title' => 'AI in Foreign Language Learning and Teaching',
                'author' => 'Marcel Danesi',
                'description' => 'Danesi examines how artificial intelligence can enhance foreign language acquisition methods; discussing innovative tools developed utilizing AI technologies aimed at improving teaching practices alongside student engagement levels; thus making this text relevant among educators seeking modern approaches towards language instruction!',
                'category_id' => 2,
                'publish_date' => '2021-03-16',
                'book_path' => 'Book30.pdf',
            ],
            [
                'thumbnail' => 'Cover31.webp',
                'title' => 'The Hundred-Page Machine Learning Book',
                'author' => 'Andriy Burkov',
                'description' => 'Burkov\'s concise yet comprehensive overview introduces readers towards machine learning fundamentals; covering essential topics ranging from supervised learning techniques through neural networks—all presented clearly within just one hundred pages—making it ideal reading material suited especially well those pressed for time yet eager towards gaining knowledge quickly!',
                'category_id' => 3,
                'publish_date' => '2019-10-11',
                'book_path' => 'Book31.pdf',
            ],
            [
                'thumbnail' => 'Cover32.webp',
                'title' => 'Machine Learning Q and AI',
                'author' => 'Sebastian Raschka, PhD',
                'description' => 'Raschka addresses common questions encountered during machine learning projects while providing clear explanations backed up practical examples; ultimately enhancing understanding among practitioners navigating complexities often associated with implementing machine learning solutions effectively!',
                'category_id' => 3,
                'publish_date' => '2020-09-18',
                'book_path' => 'Book32.pdf',
            ],
            [
                'thumbnail' => 'Cover33.webp',
                'title' => 'Applied Machine Learning Solutions with Python',
                'author' => 'Siddhanta Bhatta',
                'description' => 'Bhatta\'s text focuses on practical applications involving machine learning using Python; covering various algorithms alongside real-world case studies demonstrating their effectiveness across diverse fields; thus serving as an invaluable resource aimed primarily at practitioners seeking hands-on experience within this domain!',
                'category_id' => 3,
                'publish_date' => '2021-02-16',
                'book_path' => 'Book33.pdf',
            ],
            [
                'thumbnail' => 'Cover34.webp',
                'title' => 'Mathematics For Machine Learning',
                'author' => 'Marc Peter Deisenroth, A. Aldo Faisal, Cheng Soon Ong',
                'description' => 'Deisenroth et al provide foundational understanding necessary regarding mathematical principles underpinning machine learning methodologies—including linear algebra & probability theory; thus equipping readers adequately before diving deeper into more advanced topics related directly towards implementation later on!',
                'category_id' => 3,
                'publish_date' => '2020-08-19',
                'book_path' => 'Book34.pdf',
            ],
            [
                'thumbnail' => 'Cover35.webp',
                'title' => 'Introduction to Machine Learning with Python',
                'author' => 'Deepti Chopra, Roopal Khurana',
                'description' => 'Chopra et al introduce readers towards machine learning basics utilizing Python effectively; covering essential algorithms alongside best practices aimed at building predictive models successfully—all presented clearly through engaging examples reinforcing key concepts throughout!',
                'category_id' => 3,
                'publish_date' => '2021-07-20',
                'book_path' => 'Book35.pdf',
            ],
            [
                'thumbnail' => 'Cover36.webp',
                'title' => 'Probabilistic Machine Learning for Finance and Investing',
                'author' => 'Deepak K. Kanungo',
                'description' => 'Kanungo explores probabilistic approaches applied specifically within finance & investment sectors; discussing methodologies employed enhancing decision-making processes while addressing challenges faced during implementation—making it relevant reading material finance professionals interested leveraging advanced analytical techniques!',
                'category_id' => 3,
                'publish_date' => '2022-07-17',
                'book_path' => 'Book36.pdf',
            ],
            [
                'thumbnail' => 'Cover37.webp',
                'title' => 'Handbook of Evolutionary Machine Learning',
                'author' => 'Wolfgang Banzhaf, Penousal Machado, Mengjie Zhang',
                'description' => 'Banzhaf et al present comprehensive insights regarding evolutionary algorithms utilized within machine learning contexts; discussing theoretical foundations alongside practical applications aimed at solving complex problems effectively across diverse fields!',
                'category_id' => 3,
                'publish_date' => '2019-08-13',
                'book_path' => 'Book37.pdf',
            ],
            [
                'thumbnail' => 'Cover38.webp',
                'title' => 'Machine Learning for Kids',
                'author' => 'Dale Lane',
                'description' => 'Lane\'s engaging guide introduces children towards machine learning concepts through fun projects designed encourage creativity while developing critical thinking skills early on—ultimately fostering interest among younger generations towards technology careers later down road!',
                'category_id' => 3,
                'publish_date' => '2018-04-18',
                'book_path' => 'Book38.pdf',
            ],
            [
                'thumbnail' => 'Cover39.webp',
                'title' => 'MACHINE LEARNING FOR ALGORITHM TRADING',
                'author' => 'Jason Test, Mark Broker',
                'description' => 'Test et al focus specifically on applying machine learning techniques algorithmic trading strategies; providing insights regarding model development alongside performance evaluation aimed primarily at traders seeking enhance profitability within financial markets today!',
                'category_id' => 3,
                'publish_date' => '2020-03-15',
                'book_path' => 'Book39.pdf',
            ],
            [
                'thumbnail' => 'Cover40.webp',
                'title' => 'Python for Algorithmic Trading: From Idea to Cloud Deployment',
                'author' => 'Yves Hilpisch',
                'description' => 'Hilipch\'s comprehensive guide takes readers step-by-step through developing algorithmic trading strategies utilizing Python—from initial idea generation all way deployment cloud environments ensuring scalability & reliability throughout process!',
                'category_id' => 3,
                'publish_date' => '2019-12-19',
                'book_path' => 'Book40.pdf',
            ],

            [
                'thumbnail' => 'Cover42.webp',
                'title' => 'Learning Ray: Flexible Distributed Python for Machine Learning',
                'author' => 'Max Pumperla, Edward Oakes, Richard Liaw',
                'description' => 'Pumperla et al introduce Ray framework designed facilitate distributed computing tasks efficiently utilizing Python effectively; covering essential features aimed particularly at enhancing scalability across machine learning workloads ensuring optimal performance overall!',
                'category_id' => 3,
                'publish_date' => '2021-11-17',
                'book_path' => 'Book42.pdf',
            ],
            [
                'thumbnail' => 'Cover43.webp',
                'title' => 'Natural Language Processing with Transformers',
                'author' => 'Lewis Tunstall, Leandro von Werra, Thomas Wolf',
                'description' => 'Tunstall et al provide practical guidance towards utilizing transformer models specifically natural language processing tasks; covering core principles along hands-on examples reinforcing understanding among practitioners navigating complexities often associated NLP projects today!',
                'category_id' => 3,
                'publish_date' => '2022-01-19',
                'book_path' => 'Book43.pdf',
            ],
            [
                'thumbnail' => 'Cover44.webp',
                'title' => 'Machine Learning: Neural Networks Decision Trees and Support Vector Machine with IBM SPSS Modeler',
                'author' => 'Marvin L.',
                'description' => 'Marvin L\'s text covers various machine learning techniques including neural networks decision trees support vector machines utilizing IBM SPSS Modeler effectively throughout process ensuring accessibility among practitioners regardless prior experience levels encountered before diving deeper into subject matter overall!',
                'category_id' => 3,
                'publish_date' => '2020-04-12',
                'book_path' => 'Book44.pdf',
            ],
            [
                'thumbnail' => 'Cover45.webp',
                'title' => 'A Practical Guide to Quantum Machine Learning and Quantum Optimization',
                'author' => 'Elias F. Combarro, Samuel Gonzalez-Castillo',
                'description' => 'Combarro et al explore quantum computing principles applied directly towards machine learning tasks discussing methodologies employed optimizing performance across diverse fields ensuring relevance amid growing interest surrounding quantum technologies today!',
                'category_id' => 3,
                'publish_date' => '2021-05-11',
                'book_path' => 'Book45.pdf',
            ],
            [
                'thumbnail' => 'Cover46.webp',
                'title' => 'Guide to Deep Learning basics',
                'author' => 'Sandro Skansi (editor)',
                'description' => 'Skansi\'s edited volume presents foundational knowledge required understand deep learning principles clearly while covering essential topics necessary equip readers adequately before diving deeper into more advanced subjects later down road overall ensuring accessibility throughout process itself!',
                'category_id' => 4,
                'publish_date' => '2019-11-11',
                'book_path' => 'Book46.pdf',
            ],
            [
                'thumbnail' => 'Cover48.webp',
                'title' => 'Neural Networks and Deep Learning: A Textbook',
                'author' => 'Charu C. Aggarwal',
                'description' => 'Aggarwal presents detailed examination neural network architectures along deep learning techniques emphasizing theoretical foundations alongside real-world applications making this text invaluable resources students aspiring delve deeper subject matter overall ensuring thorough comprehension overall throughout process itself itself!',
                'category_id' => 4,
                'publish_date' => '2018-06-13',
                'book_path' => 'Book48.pdf',
            ],
            [
                'thumbnail' => 'Cover49.webp',
                'title' => 'Deep Learning',
                'author' => 'Ian Goodfellow, Yoshua Bengio, Aaron Courville',
                'description' => 'Goodfellow et al offer authoritative exploration deep learning theories practices written leading experts field covering wide range topics including neural networks optimization strategies thus serving vital reference material both newcomers veterans alike seeking enhance knowledge further overall throughout journey itself itself!',
                'category_id' => 4,
                'publish_date' => '2016-05-15',
                'book_path' => 'Book49.pdf',
            ],
            [
                'thumbnail' => 'Cover50.webp',
                'title' => 'Understanding Deep Learning',
                'author' => 'Simon J.D. Prince',
                'description' => 'Prince aims demystify complexities surrounding deep learning principles presenting clear explanations backed up practical examples ultimately fostering deeper appreciation subject matter among audience eager learn more regarding technology rapidly evolving landscape overall ensuring thorough comprehension throughout journey itself!',
                'category_id' => 4,
                'publish_date' => '2019-03-18',
                'book_path' => 'Book50.pdf',
            ],
            [
                'thumbnail' => 'Cover51.webp',
                'title' => 'An Introduction to Neural Networks',
                'author' => 'James A. Anderson',
                'description' => 'An Introduction to Neural Networks falls into a new ecological niche for texts. Based on notes that have been class-tested for more than a decade, it is aimed at cognitive science and neuroscience students who need to understand brain function in terms of computational modeling, and at engineers who want to go beyond formal algorithms to applications and computing strategies. It is the only current text to approach networks from a broad neuroscience and cognitive science perspective, with an emphasis on the biology and psychology behind the assumptions of the models, as well as on what the models might be used for. It describes the mathematical and computational tools needed and provides an account of the author\'s own ideas.Students learn how to teach arithmetic to a neural network and get a short course on linear associative memory and adaptive maps. They are introduced to the author\'s brain-state-in-a-box (BSB) model and are provided with some of the neurobiological background necessary [...]for a firm grasp of the general subject.The field now known as neural networks has split in recent years into two major groups, mirrored in the texts that are currently available: the engineers who are primarily interested in practical applications of the new adaptive, parallel computing technology, and the cognitive scientists and neuroscientists who are interested in scientific applications. As the gap between these two groups widens, Anderson notes that the academics have tended to drift off into irrelevant, often excessively abstract research while the engineers have lost contact with the source of ideas in the field. Neuroscience, he points out, provides a rich and valuable source of ideas about data representation and setting up the data representation is the major part of neural network programming. Both cognitive science and neuroscience give insights into how this can be done effectively: cognitive science suggests what to compute and neuroscience suggests how to compute it.',
                'category_id' => 4,
                'publish_date' => '1995-06-19',
                'book_path' => 'Book51.pdf',
            ],
            [
                'thumbnail' => 'Cover52.webp',
                'title' => 'Neural Networks with Python',
                'author' => 'Mei Wong',
                'description' => 'This book serves as an introductory guide for those taking their first steps into neural network development with Python. It\'s tailored to assist beginners in understanding the foundational elements of neural networks and to provide them with the confidence to delve deeper into this intriguing area of machine learning. In this book, readers will embark on a learning journey, starting from the very basics of Python programming, progressing through essential concepts, and gradually building up to more complex neural network architectures. The book simplifies the learning process by using relatable examples and datasets, making the concepts accessible to everyone. You will be introduced to various neural network architectures such as Feedforward, Convolutional, and Recurrent Neural Networks, among others. Each type is explained in a clear and concise manner, with practical examples to illustrate their applications. The book emphasizes the real-world applications and practical aspects of neural network development, rather than just theoretical knowledge. Readers will also find guidance on how to troubleshoot and refine their neural network models. The goal is to equip you with a solid understanding of how to create efficient and effective neural networks, while also being mindful of the common challenges that may arise. By the end of your journey with this book, you will have a foundational understanding of neural networks within the Python ecosystem and be prepared to apply this knowledge to real-world scenarios. "Neural Networks with Python" aims to be your stepping stone into the vast world of machine learning, empowering you to build upon this knowledge and explore more advanced topics in the future. Key Learnings: Master Python for Machine Learning, from setup to complex models. Gain flexibility with diverse neural network architectures for various problems. Hands-on experience in building, training, and fine-tuning neural networks. Learn strategic approaches for troubleshooting and optimizing neural models. Grasp advanced topics like autoencoders, capsule networks, and attention mechanisms. Acquire skills in crucial data preprocessing and augmentation techniques. Understand and apply optimization techniques and hyperparameter tuning. Implement an end-to-end machine learning project, from data to deployment.',
                'category_id' => 4,
                'publish_date' => '2020-06-23',
                'book_path' => 'Book52.pdf',
            ],
            [
                'thumbnail' => 'Cover53.webp',
                'title' => 'Neural networks with R',
                'author' => 'Balaji Venkateswaran, Francesco Ciabuschi',
                'description' => 'This book introduces readers to the implementation of neural networks using the R programming language. Venkateswaran and Ciabuschi cover fundamental concepts of neural networks, including architecture design, training algorithms, and performance evaluation. With practical examples and case studies, the authors demonstrate how to apply these techniques to various data analysis tasks, making it a valuable resource for data scientists and statisticians.',
                'category_id' => 4,
                'publish_date' => '2019-05-27',
                'book_path' => 'Book53.pdf',
            ],
            [
                'thumbnail' => 'Cover55.webp',
                'title' => 'Practical Mathematics for AI and Deep Learning',
                'author' => 'Tamoghna Ghosh, Shravan Kumar Belagal Math',
                'description' => 'This text provides a practical approach to the mathematical concepts essential for artificial intelligence and deep learning. Ghosh and Belagal cover topics such as linear algebra, calculus, probability, and statistics while emphasizing their applications in AI algorithms. The book is designed to equip readers with the necessary mathematical tools to understand and implement deep learning models effectively.',
                'category_id' => 4,
                'publish_date' => '2022-07-21',
                'book_path' => 'Book55.pdf',
            ],
            [
                'thumbnail' => 'Cover56.webp',
                'title' => 'Deep Learning Approach for Natural Language Processing, Speech, and Computer Vision',
                'author' => 'L. Ashok Kumar, D. Karthika Renuka',
                'description' => 'Deep Learning Approach for Natural Language Processing, Speech, and Computer Vision provides an overview of general deep learning methodology and its applications of Natural Language Processing (NLP), speech and Computer Vision tasks. It simplifies and presents the concepts of Deep Learning in a comprehensive manner, with suitable, full-fledged examples of Deep Learning models, with an aim to bridge the gap between the theory and the applications using case studies with code, experiments, and supporting analysis. Voice-based assistants, AI-based chatbots, and advanced driver assistance systems are examples of applications that are becoming more common in daily life. In particular, the profound success of deep learning in a wide variety of domains has served as a benchmark for the many downstream applications in Artificial Intelligence (AI). Application areas of AI include natural language processing (NLP), speech, and computer vision. The cutting-edge deep learning models have predominantly changed the perspectives of varied fields in AI, including speech, vision, and NLP. In this book, we made an attempt to explore the more recent developments of deep learning in the field of NLP, speech, and computer vision. With the knowledge in this book, the reader can understand the intuition behind the working of natural language applications, speech, and computer vision applications. NLP is a part of AI that makes computers to interpret the meaning of human language. NLP utilizes machine learning and deep learning algorithms to derive the context behind the raw text. Computer vision applications such as advanced driver assistance systems, augmented reality, virtual reality, and biometrics have advanced significantly. With the advances in deep learning and neural networks, the field of computer vision has made great strides in the last decade and now outperforms humans in tasks such as object detection and labeling. This book gives an easy understanding of the fundamental concepts of underlying deep learning algorithms to the students, researchers, and industrial researchers as well as anyone interested in deep learning and NLP. It serves as a source of motivation for those who want to create NLP, speech, and computer vision applications. Features: - Covers latest developments in Deep Learning techniques as applied to audio analysis, Computer Vision, and Natural Language Processing - Introduces contemporary applications of Deep Learning techniques as applied to audio, textual, and visual processing - Discovers Deep Learning frameworks and libraries for NLP, speech and computer vision in Python - Gives insights into using the tools and libraries in Python for real-world applications - Provides easily accessible tutorials, and real-world case studies with codes to provide hands-on experience This book is aimed at researchers and graduate students in computer engineering, image, speech, and text processing.',
                'category_id' => 4,
                'publish_date' => '2021-08-29',
                'book_path' => 'Book56.pdf',
            ],

            [
                'thumbnail' => 'Cover58.webp',
                'title' => 'Learn Python Generative AI',
                'author' => 'Zonunfeli Ralte, Indrajit Kar',
                'description' => 'Learn to unleash the power of AI creativity',
                'category_id' => 4,
                'publish_date' => '2023-05-30',
                'book_path' => 'Book58.pdf',
            ],
            [
                'thumbnail' => 'Cover59.webp',
                'title' => 'Generative Deep Learning',
                'author' => 'David Foster',
                'description' => 'Generative AI is the hottest topic in tech. This practical book teaches machine learning engineers and data scientists how to create impressive generative deep learning models from scratch using Tensorflow and Keras, including variational autoencoders (VAEs), generative adversarial networks (GANs), Transformers, normalizing flows, energy-based models, and denoising diffusion models. The book starts with the basics of deep learning and progresses to cutting-edge architectures. Through tips and tricks, readers can make their models learn more efficiently and become more creative.',
                'category_id' => 4,
                'publish_date' => '2021-10-19',
                'book_path' => 'Book59.pdf',
            ],
            [
                'thumbnail' => 'Cover60.webp',
                'title' => 'Deep Learning with Azure',
                'author' => 'Mathew Salvaris, Danielle Dean, Wee Hyong Tok',
                'description' => 'Get up-to-speed with Microsoft\'s AI Platform. Learn to innovate and accelerate with open and powerful tools and services that bring artificial intelligence to every data scientist and developer. Artificial Intelligence (AI) is the new normal. Innovations in deep learning algorithms and hardware are happening at a rapid pace. It is no longer a question of should I build AI into my business, but more about where do I begin and how do I get started with AI? Written by expert data scientists at Microsoft, Deep Learning with the Microsoft AI Platform helps you with the how-to of doing deep learning on Azure and leveraging deep learning to create innovative and intelligent solutions. Benefit from guidance on where to begin your AI adventure, and learn how the cloud provides you with all the tools, infrastructure, and services you need to do AI.',
                'category_id' => 4,
                'publish_date' => '2020-09-16',
                'book_path' => 'Book60.pdf',
            ],
        ];

        foreach($books as $book) {
            $thumbnailSource = database_path('seeders/resources/Books/Thumbnail/' . basename($book['thumbnail']));
            $bookPathSource = database_path('seeders/resources/Books/Data/' . basename($book['book_path']));

            if (file_exists($thumbnailSource)) {
                Storage::disk('public')->put('Books/Thumbnail/' . basename($book['thumbnail']), file_get_contents($thumbnailSource));
            }

            if (file_exists($bookPathSource)) {
                Storage::disk('public')->put('Books/Data/' . basename($book['book_path']), file_get_contents($bookPathSource));
            }

            DB::table('books')->insert([
                'thumbnail' => 'Books/Thumbnail/' . basename($book['thumbnail']),
                'title' => $book['title'],
                'author' => $book['author'],
                'description' => $book['description'],
                'category_id' => $book['category_id'],
                'publish_date' => $book['publish_date'],
                'book_path' => 'Books/Data/' . basename($book['book_path']),
            ]);
        }
    }
}
