<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class VideoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $videos = [
            [
                'thumbnail' => 'Video1.jpg',
                'title' => 'C Programming Tutorial for Beginners',
                'creator' => 'freeCodeCamp.org',
                'description' => 'This course will give you a full introduction into all of the core concepts in the C programming language.',
                'category_id' => 1,
                'publish_date' => '2018-08-16',
                'url' => 'https://youtu.be/KJgsSFOSQv0?si=nupANn5OTZVMnt-z',
            ],
            [
                'thumbnail' => 'Video2.jpg',
                'title' => 'C in 100 Seconds',
                'creator' => 'Fireship',
                'description' => 'The C Programming Language is quite possibly the most influential language of all time. It powers OS kernels like Linux, Windows, and Mac and many other low-level systems.  Its syntax has inspired many other languages, including Cpp, Csharp, Java, JavaScript, Go, Perl, and more.  ',
                'category_id' => 1,
                'publish_date' => '2021-11-10',
                'url' => 'https://youtu.be/U3aXWizDbQ4?si=Y_mg268KZWOtgHoP',
            ],
            [
                'thumbnail' => 'Video3.jpg',
                'title' => 'Maths for Programmers Tutorial - Full Course on Sets and Logic',
                'creator' => 'freeCodeCamp.org',
                'description' => 'Learn the maths and logic concepts that are important for programmers to understand.',
                'category_id' => 1,
                'publish_date' => '2018-10-01',
                'url' => 'https://youtu.be/2SpuBqvNjHI?si=xhupCAPf1LVlPW5U',
            ],
            [
                'thumbnail' => 'Video4.jpg',
                'title' => 'Data Structures Easy to Advanced Course - Full Tutorial from a Google Engineer',
                'creator' => 'freeCodeCamp.org',
                'description' => 'Learn and master the most common data structures in this full course from Google engineer William Fiset. This course teaches data structures to beginners using high quality animations to represent the data structures visually.',
                'category_id' => 1,
                'publish_date' => '2019-09-19',
                'url' => 'https://youtu.be/RBSGKlAvoiM?si=QOvO95okz88mbmZX',
            ],
            [
                'thumbnail' => 'Video5.jpg',
                'title' => 'Harvard CS50 (2023) - Full Computer Science University Course',
                'creator' => 'freeCodeCamp.org',
                'description' => 'Learn the basics of computer science from Harvard University. This is CS50, an introduction to the intellectual enterprises of computer science and the art of programming. The course is taught live every year and this is the 2023 version.',
                'category_id' => 1,
                'publish_date' => '2023-10-24',
                'url' => 'https://youtu.be/LfaMVlDaQ24?si=Ef_zyg896y9TL8e8',
            ],
            [
                'thumbnail' => 'Video6.jpg',
                'title' => '10 years of coding in 13 minutes',
                'creator' => 'Joma Tech',
                'description' => 'Thanks #GrowWithGoogle for sponsoring this video. ',
                'category_id' => 1,
                'publish_date' => '2021-10-19',
                'url' => 'https://youtu.be/1fPWr0d5zBE?si=sSdF9wckG8F5bOCG',
            ],
            [
                'thumbnail' => 'Video7.jpg',
                'title' => '3.6 Dijkstra Algorithm - Single Source Shortest Path - Greedy Method',
                'creator' => 'Abdul Bari',
                'description' => 'Dijkstra Algorithm for Single Source Shortest Path',
                'category_id' => 1,
                'publish_date' => '2018-02-10',
                'url' => 'https://youtu.be/XB4MIexjvY0?si=e8aeqggDGPRUNNCq',
            ],
            [
                'thumbnail' => 'Video8.jpg',
                'title' => 'The hidden beauty of the A* algorithm',
                'creator' => 'Polylog',
                'description' => 'One thing I did not mention is that Dijkstra\'s algorithm is designed to solve the problem of finding the shortest path from the start node to all other nodes of the graph. It does this job very well, in almost linear time, so there is not much to improve there. It is the problem of finding the shortest path between two nodes where A* usually improves upon Dijkstra.',
                'category_id' => 1,
                'publish_date' => '2023-01-21',
                'url' => 'https://youtu.be/A60q6dcoCjw?si=SXu-Ig_j-GCCHUkN',
            ],
            [
                'thumbnail' => 'Video9.jpg',
                'title' => 'Algorithms and Data Structures Tutorial - Full Course for Beginners',
                'creator' => 'freeCodeCamp.org',
                'description' => 'In this course you will learn about algorithms and data structures, two of the fundamental topics in computer science. There are three main parts to this course: algorithms, data structures, and a deep dive into sorting and searching algorithms.',
                'category_id' => 1,
                'publish_date' => '2021-03-19',
                'url' => 'https://youtu.be/8hly31xKli0?si=tPOOfTSVRU2m29LH',
            ],
            [
                'thumbnail' => 'Video10.jpg',
                'title' => 'Discrete Mathematics (Full Course)',
                'creator' => 'My Lesson',
                'description' => 'Discrete mathematics forms the mathematical foundation of computer and information science. It is also a fascinating subject in itself.',
                'category_id' => 1,
                'publish_date' => '2022-05-13',
                'url' => 'https://youtu.be/UwYJUKVc-Hs?si=YzVV5uYyd0dUgfAb',
            ],
            [
                'thumbnail' => 'Video11.jpg',
                'title' => 'Python Full Course for free',
                'creator' => 'Bro Code',
                'description' => 'Python tutorial for beginners full course',
                'category_id' => 1,
                'publish_date' => '2021-02-15',
                'url' => 'https://youtu.be/XKHEtdqhLK8?si=jnzKGHZM3jNz2Eb2',
            ],
            [
                'thumbnail' => 'Video12.jpg',
                'title' => 'Java Full Course for free ',
                'creator' => 'Bro Code',
                'description' => 'Java tutorial for beginners full course',
                'category_id' => 1,
                'publish_date' => '2020-11-09',
                'url' => 'https://youtu.be/xk4_1vDrzzo?si=9dT4kGt7XImg-c2e',
            ],
            [
                'thumbnail' => 'Video13.jpg',
                'title' => 'C++ Full Course for free',
                'creator' => 'Bro Code',
                'description' => 'C++ tutorial for beginners full course',
                'category_id' => 1,
                'publish_date' => '2022-06-29',
                'url' => 'https://youtu.be/-TkoO8Z07hI?si=mLellFhZJERTLBMy',
            ],
            [
                'thumbnail' => 'Video14.jpg',
                'title' => 'HTML & CSS Full Course for free',
                'creator' => 'Bro Code',
                'description' => 'HTML & CSS tutorial for beginners full course',
                'category_id' => 1,
                'publish_date' => '2023-05-31',
                'url' => 'https://youtu.be/HGTJBPNC-Gw?si=Gsiin476Ag4vpwMi',
            ],
            [
                'thumbnail' => 'Video15.jpg',
                'title' => 'JavaScript Full Course for free (2024)',
                'creator' => 'Bro Code',
                'description' => 'JavaScript tutorial for beginners full course',
                'category_id' => 1,
                'publish_date' => '2024-01-01',
                'url' => 'https://youtu.be/lfmg-EJ8gm4?si=2XQmVktfXm_vYwhg',
            ],
            [
                'thumbnail' => 'Video16.jpg',
                'title' => 'Harvard CS50\'s Artificial Intelligence with Python - Full University Course',
                'creator' => 'freeCodeCamp.org',
                'description' => 'This course from Harvard University explores the concepts and algorithms at the foundation of modern artificial intelligence, diving into the ideas that give rise to technologies like large language models, game-playing engines, handwriting recognition, and machine translation. Through hands-on projects, students gain exposure to the theory behind graph search algorithms, classification, optimization, reinforcement learning, and other topics in artificial intelligence and machine learning as they incorporate them into their own Python programs.',
                'category_id' => 2,
                'publish_date' => '2023-08-10',
                'url' => 'https://youtu.be/5NgNicANyqM?si=uNi0doo8NBaWzCQ_',
            ],
            [
                'thumbnail' => 'Video17.jpg',
                'title' => 'Generative AI Full Course - Gemini Pro, OpenAI, Llama, Langchain, Pinecone, Vector Databases & More',
                'creator' => 'freeCodeCamp.org',
                'description' => 'Learn about generative models and different frameworks, investigating the production of text and visual material produced by artificial intelligence. This course was originally recorded live.',
                'category_id' => 2,
                'publish_date' => '2024-02-27',
                'url' => 'https://youtu.be/mEsleV16qdo?si=Qpy0e7RvWrXqMCzv',
            ],
            [
                'thumbnail' => 'Video18.jpg',
                'title' => 'Artificial Intelligence Full Course 2024 | AI Course For Absolute Beginners | Simplilearn',
                'creator' => 'Simplilearn',
                'description' => 'This video on the Artificial Intelligence full course video cover all the topics you need to know to become a master in AI and ML. It covers all the basics of Machine Learning, the different types of Machine Learning, and the various applications of Machine Learning used in different industries. This video will also help us understand the basics of artificial intelligence. We will look at the future of AI and listen to some of the industry experts and learn what they have to say about AI. Finally, you will learn the Top 10 Artificial Intelligence Technologies. ',
                'category_id' => 2,
                'publish_date' => '2024-09-24',
                'url' => 'https://youtu.be/zkubwWb3m4Q?si=IZRXFdIZqLhLhTcE',
            ],
            [
                'thumbnail' => 'Video19.jpg',
                'title' => 'What Is AI? | Artificial Intelligence | What is Artificial Intelligence? | AI In 5 Mins |Simplilearn',
                'creator' => 'Simplilearn',
                'description' => '
This video on What is Artificial Intelligence will give you a brief overview of artificial intelligence as a technology in just 5 minutes. We will start with a minor introduction to artificial intelligence in which we will know what is artificial intelligence with the help of examples. Moving ahead we will see what are the uses of AI, what is strong AI and what is weak AI. We will warp up this video by making you understand the major difference between AI ML and Deep Learning which will be followed by the future scope of artificial intelligence.',
                'category_id' => 2,
                'publish_date' => '2019-04-30',
                'url' => 'https://youtu.be/ad79nYk2keg?si=LMxUmM_ZYtOxjXWG',
            ],
            [
                'thumbnail' => 'Video20.jpg',
                'title' => 'Building a Language Model with A Turtle',
                'creator' => 'Tutel',
                'description' => 'The Twitch streamer Vedal has created an AI called Neuro-Sama and at the end of the subathon they built a language model from scratch while following a tutorial from Andrej Karpathy',
                'category_id' => 2,
                'publish_date' => '2024-01-27',
                'url' => 'https://youtu.be/fatAMpWM2sQ?si=K2S0JJ6lJd5DFaEd',
            ],
            [
                'thumbnail' => 'Video21.jpg',
                'title' => 'Artificial Intelligence Full Course in 10 Hours [2024] | Artificial Intelligence Tutorial | Edureka',
                'creator' => 'edureka!',
                'description' => 'This Edureka video on "Artificial Intelligence Full Course" will provide you with a comprehensive and detailed knowledge of Artificial Intelligence concepts with hands-on examples.',
                'category_id' => 2,
                'publish_date' => '2023-02-18',
                'url' => 'https://www.youtube.com/live/VOaoabf3LPM?si=ltHYANcs29sVvLEA',
            ],
            [
                'thumbnail' => 'Video22.jpg',
                'title' => 'Generative AI in a Nutshell - how to survive and thrive in the age of AI',
                'creator' => 'Henrik Kniberg',
                'description' => 'Basically a full day AI course crammed into 18 mins of drawing & talking. Target audience: Everyone.',
                'category_id' => 2,
                'publish_date' => '2024-01-20',
                'url' => 'https://youtu.be/2IK3DFHRFfw?si=Y6_5NttSvKV-Ckys',
            ],
            [
                'thumbnail' => 'Video23.jpg',
                'title' => 'How does artificial intelligence learn? - Briana Brownell',
                'creator' => 'TED-Ed',
                'description' => 'Today, artificial intelligence helps doctors diagnose patients, pilots fly commercial aircraft, and city planners predict traffic. These AIs are often self-taught, working off a simple set of instructions to create a unique array of rules and strategies. So how exactly does a machine learn? Briana Brownell digs into the three basic ways machines investigate, negotiate, and communicate.',
                'category_id' => 2,
                'publish_date' => '2021-03-11',
                'url' => 'https://youtu.be/0yCJMt9Mx9c?si=rLblUeDc1QH282Nn',
            ],
            [
                'thumbnail' => 'Video24.jpg',
                'title' => 'i taught an AI to solve the trolley problem',
                'creator' => 'Answer in Progress',
                'description' => 'Can you teach a machine to be a good person? In this video, Sabrina explores the world of AI ethics and tries to teach a machine to solve the trolley problem. It doesn\'t go well.',
                'category_id' => 2,
                'publish_date' => '2021-06-11',
                'url' => 'https://youtu.be/181Nj060xMQ?si=7k1sdN8ld9n35_DC',
            ],
            [
                'thumbnail' => 'Video25.jpg',
                'title' => 'AI vs Machine Learning',
                'creator' => 'IBM Technology',
                'description' => 'What is really the difference between Artificial intelligence (AI) and machine learning (ML)? Are they actually the same thing? In this video, Jeff Crume explains the differences and relationship between AI & ML, as well as how related topics like Deep Learning (DL) and other types and properties of each.',
                'category_id' => 2,
                'publish_date' => '2023-04-10',
                'url' => 'https://youtu.be/4RixMPF4xis?si=ZtbLLL_yWz-J4PCc',
            ],
            [
                'thumbnail' => 'Video26.jpg',
                'title' => 'AI Foundations Course - Python, Machine Learning, Deep Learning, Data Science',
                'creator' => 'freeCodeCamp.org',
                'description' => 'Learn about machine learning and AI with this comprehensive 11-hour course from ‪@LunarTech_ai‬. This is not just a crash course. This course covers everything from fundamental concepts to advanced algorithms, complete with real-world case studies in recommender systems and predictive analytics. This course goes beyond theory to provide hands-on implementation experience, career guidance, and great insights from industry professionals. It also includes a career guide on how to build a data science career, launch a startup, and prepare for interviews.',
                'category_id' => 2,
                'publish_date' => '2024-11-05',
                'url' => 'https://youtu.be/0oyDqO8PjIg?si=tLI5166_0PLwt_WX',
            ],
            [
                'thumbnail' => 'Video27.jpg',
                'title' => 'AI Machine Learning Roadmap: Self Study AI!',
                'creator' => 'Exaltitude',
                'description' => 'Unlock the secrets to mastering Artificial Intelligence (AI) quickly with this self-study roadmap, based on the prestigious Stanford AI Graduate Certificate program\'s curriculum. In this video, I\'ll guide you through the essential steps, from foundational math to building your own AI projects. Whether you\'re interested in machine learning, robotics, or AI fundamentals, this structured approach is designed to help you learn at your own pace, all for free.
You\'ll learn how to choose the right AI algorithms, implement models with Python and TensorFlow, and work on machine learning capstone projects that can showcase your skills as an AI / ML Engineer. Perfect for anyone looking to fast-track their AI Engineering / ML Engineering career or AI self-study journey!',
                'category_id' => 2,
                'publish_date' => '2024-10-28',
                'url' => 'https://youtu.be/nznFtfgP2ks?si=ptzqWxz47w5eJgSu',
            ],
            [
                'thumbnail' => 'Video28.jpg',
                'title' => 'How to Build AI Chatbots: Full Guide from Beginner to Pro (Latest Update)',
                'creator' => 'Bo Sar',
                'description' => 'In this comprehensive video, I provide an in-depth guide to mastering AI chatbots. You\'ll learn about their functionality, development, and the best business use cases. Additionally, I review notable updates in the AI field and offer tutorials on building chatbots using various tools.',
                'category_id' => 2,
                'publish_date' => '2024-07-30',
                'url' => 'https://youtu.be/SWP3k-24jT4?si=q-kC0eVUCjXiJbik',
            ],
            [
                'thumbnail' => 'Video29.jpg',
                'title' => 'How AI works in everyday life | Google AI',
                'creator' => 'Google',
                'description' => 'Find out how machines learn to help you with everyday interactions with technology products. This is an excerpt from a larger lesson, “Discover AI in Daily Life," from Applied Digital Skills, Google\'s free, online, video-based curriculum.',
                'category_id' => 2,
                'publish_date' => '2022-02-23',
                'url' => 'https://youtu.be/oJC8VIDSx_Q?si=UxAq--FY82LUK8KS',
            ],
            [
                'thumbnail' => 'Video30.jpg',
                'title' => 'What are AI Agents?',
                'creator' => 'IBM Technology',
                'description' => 'In this video, Maya Murad explores the evolution of AI agents and their pivotal role in revolutionizing AI systems. From monolithic models to compound AI systems, discover how AI agents integrate with databases and external tools to enhance problem-solving capabilities and adaptability.',
                'category_id' => 2,
                'publish_date' => '2024-07-15',
                'url' => 'https://youtu.be/F8NKVhkZZWI?si=DaJBSdg-WPn1S_1M',
            ],
            [
                'thumbnail' => 'Video31.jpg',
                'title' => 'Machine Learning for Everybody - Full Course',
                'creator' => 'freeCodeCamp.org',
                'description' => 'Learn Machine Learning in a way that is accessible to absolute beginners. You will learn the basics of Machine Learning and how to use TensorFlow to implement many different concepts.',
                'category_id' => 3,
                'publish_date' => '2022-09-26',
                'url' => 'https://youtu.be/i_LwzRVP7bg?si=DWWMas4gVwcc73De',
            ],
            [
                'thumbnail' => 'Video32.jpg',
                'title' => 'All Machine Learning algorithms explained in 17 min',
                'creator' => 'Infinite Codes',
                'description' => 'In this video I will go through all machine learning algorithms in less than 17 minutes to get you an intuitive understanding of how they work and how they relate to each other as well as help you decide how to pick the right one for your problem. Going all the way from Linear Regression to Neural Networks / Deep Learning and Unsupervised Learning.',
                'category_id' => 3,
                'publish_date' => '2024-09-17',
                'url' => 'https://youtu.be/E0Hmnixke2g?si=x3IXWQx9g6aDZVeB',
            ],
            [
                'thumbnail' => 'Video33.jpg',
                'title' => 'Machine Learning Full Course - Learn Machine Learning 10 Hours | Machine Learning Tutorial | Edureka',
                'creator' => 'edureka!',
                'description' => 'This Edureka Machine Learning Full Course video will help you understand and learn Machine Learning Algorithms in detail. This Machine Learning Tutorial is ideal for both beginners as well as professionals who want to master Machine Learning Algorithms. ',
                'category_id' => 3,
                'publish_date' => '2019-09-22',
                'url' => 'https://youtu.be/GwIo3gDZCVQ?si=Twmr-1P8F-RUFS9h',
            ],
            [
                'thumbnail' => 'Video34.jpg',
                'title' => 'Machine Learning with Python and Scikit-Learn - Full Course',
                'creator' => 'freeCodeCamp.org',
                'description' => 'We\'ll start with the basics of machine learning by exploring models like linear & logistic regression and then move on to tree-based models like decision trees, random forests, and gradient-boosting machines. We\'ll also discuss best practices for approaching and managing machine learning projects and build a state-of-the-art machine learning model for a real-world dataset from scratch. We\'ll also look at unsupervised learning & recommendations briefly and walk through the process of deploying a machine-learning model to the cloud using the Flask web framework.',
                'category_id' => 3,
                'publish_date' => '2023-11-22',
                'url' => 'https://youtu.be/hDKCxebp88A?si=ARuzId_rFBJxe7Si',
            ],
            [
                'thumbnail' => 'Video35.jpg',
                'title' => 'Machine Learning Course for Beginners',
                'creator' => 'freeCodeCamp.org',
                'description' => 'Learn the theory and practical application of machine learning concepts in this comprehensive course for beginners.',
                'category_id' => 3,
                'publish_date' => '2021-08-30',
                'url' => 'https://youtu.be/NWONeJKn6kc?si=6zg-PfNcdrPK2z7T',
            ],
            [
                'thumbnail' => 'Video36.jpg',
                'title' => 'Random Forest Algorithm Clearly Explained!',
                'creator' => 'Normalized Nerd',
                'description' => 'Here, I\'ve explained the Random Forest Algorithm with visualizations. You\'ll also learn why the random forest is more robust than decision trees.',
                'category_id' => 3,
                'publish_date' => '2021-04-21',
                'url' => 'https://youtu.be/v6VJ2RO66Ag?si=chCV3tn2yosu4-uk',
            ],
            [
                'thumbnail' => 'Video37.jpg',
                'title' => 'Random Forest Algorithm - Random Forest Explained | Random Forest in Machine Learning | Simplilearn',
                'creator' => 'Simplilearn',
                'description' => 'This Random Forest Algorithm tutorial will explain how the Random Forest algorithm works. By the end of this video, you will be able to understand what is Machine Learning, what is a Classification problem,  applications of Random Forest, why we need Random Forest, how it works with simple examples, and how to implement a Random Forest algorithm in Machine Learning. This video is a part of the Machine Learning with Python Series.',
                'category_id' => 3,
                'publish_date' => '2018-03-13',
                'url' => 'https://youtu.be/eM4uJ6XGnSM?si=2JKnsk3S6GZwOLsN',
            ],
            [
                'thumbnail' => 'Video38.jpg',
                'title' => 'Machine Learning | What Is Machine Learning? | Introduction To Machine Learning | 2024 | Simplilearn',
                'creator' => 'Simplilearn',
                'description' => 'This Machine Learning basics video will help you understand what Machine Learning is, what are the types of Machine Learning - supervised, unsupervised & reinforcement learning, how Machine Learning works with simple examples, and will also explain how Machine Learning is being used in various industries. Machine learning is a core sub-area of artificial intelligence; it enables computers to get into self-learning mode without being explicitly programmed. When exposed to new data, these computer programs are enabled to learn, grow, change, and develop by themselves. So, the iterative aspect of machine learning is the ability to adapt to new data independently. This is possible as programs learn from previous computations and use “pattern recognition” to produce reliable results.',
                'category_id' => 3,
                'publish_date' => '2018-09-19',
                'url' => 'https://youtu.be/ukzFI9rgwfU?si=sCdNPo30MO0J7f3m',
            ],
            [
                'thumbnail' => 'Video39.jpg',
                'title' => 'Supervised vs Unsupervised vs Reinforcement Learning | Machine Learning Tutorial | Simplilearn',
                'creator' => 'Simplilearn',
                'description' => 'In this video, you will learn about Supervised vs Unsupervised vs Reinforcement Learning. You will understand the definition of each of these learning techniques and look at the various algorithms that are part of these methods. You will see the approach and the learning methods used in the training process. Finally, you will learn the various applications of Supervised, Unsupervised, and Reinforcement Learning.',
                'category_id' => 3,
                'publish_date' => '2020-09-20',
                'url' => 'https://youtu.be/1FZ0A1QCMWc?si=DMOMUiZYqjRCAxkR',
            ],
            [
                'thumbnail' => 'Video40.jpg',
                'title' => 'Feature Selection In Machine Learning | Feature Selection Techniques With Examples | Simplilearn',
                'creator' => 'Simplilearn',
                'description' => 'In Machine Learning, not all the data you collect is useful for analysis. In this video, you will learn about Feature Selection. You will understand the need for feature selection and what is feature selection. You will look at the various feature selection methods and get an idea about feature selection statistics. Finally, you will learn how to select features using a dataset and perform analysis in Python.',
                'category_id' => 3,
                'publish_date' => '2020-11-25',
                'url' => 'https://youtu.be/5bHpPQ6_OU4?si=pmAXXru-8N1rRiPV',
            ],
            [
                'thumbnail' => 'Video41.jpg',
                'title' => 'Mathematics for Machine Learning Tutorial (3 Complete Courses in 1 video)',
                'creator' => 'My Lesson',
                'description' => '
For a lot of higher level courses in Machine Learning and Data Science, you find you need to freshen up on the basics in mathematics - stuff you may have studied before in school or university, but which was taught in another context, or not very intuitively, such that you struggle to relate it to how it\'s used in Computer Science. This specialization aims to bridge that gap, getting you up to speed in the underlying mathematics, building an intuitive understanding, and relating it to Machine Learning and Data Science   ',
                'category_id' => 3,
                'publish_date' => '2021-08-10',
                'url' => 'https://youtu.be/0z6AhrOSrRs?si=l_CYmXEGqAnLK34o',
            ],
            [
                'thumbnail' => 'Video42.jpg',
                'title' => 'What is the K-Nearest Neighbor (KNN) Algorithm?',
                'creator' => 'IBM Technology',
                'description' => '
Join Martin Keen as he provides an in-depth explanation of the K-Nearest Neighbors (KNN) algorithm, a popular classification and regression classifier in machine learning. Martin covers the basics of KNN, including its assumption that similar data points are located near each other, and how it works with examples - as well as the strengths and weaknesses of KNN, including its simplicity, adaptability, and scalability issues.',
                'category_id' => 3,
                'publish_date' => '2024-09-02',
                'url' => 'https://youtu.be/b6uHw7QW_n4?si=6wln_hSHKfh0LGGb',
            ],
            [
                'thumbnail' => 'Video43.jpg',
                'title' => 'Lecture 6 - Support Vector Machines | Stanford CS229: Machine Learning Andrew Ng (Autumn 2018)',
                'creator' => 'Stanford Online',
                'description' => '
Andrew Ng  Adjunct Professor of Computer Science',
                'category_id' => 3,
                'publish_date' => '2020-04-18',
                'url' => 'https://youtu.be/lDwow4aOrtg?si=VOEtvAyYgAKJS0at',
            ],
            [
                'thumbnail' => 'Video44.jpg',
                'title' => 'Linear Regression Algorithm - Solved Numerical Example in Machine Learning by Mahesh Huddar',
                'creator' => 'Mahesh Huddar',
                'description' => 'regression equation,
regression analysis introduction,
regression analysis,
linear regression solved example,
linear regression example,
 regression solved example,
regression numerical example,
regression numerical methods,',
                'category_id' => 3,
                'publish_date' => '2023-05-02',
                'url' => 'https://youtu.be/QcPycBZomac?si=87JJowU7UMRPcTTE',
            ],
            [
                'thumbnail' => 'Video45.jpg',
                'title' => 'Stanford CS229: Machine Learning - Linear Regression and Gradient Descent | Lecture 2 (Autumn 2018)',
                'creator' => 'Stanford Online',
                'description' => 'This lecture covers supervised learning and linear regression.',
                'category_id' => 3,
                'publish_date' => '2020-04-18',
                'url' => 'https://youtu.be/4b4MUYve_U8?si=nuRgVSGPxkUtroxs',
            ],
            [
                'thumbnail' => 'Video46.jpg',
                'title' => 'Deep Learning Crash Course for Beginners',
                'creator' => 'freeCodeCamp.org',
                'description' => 'Learn the fundamental concepts and terminology of Deep Learning, a sub-branch of Machine Learning. This course is designed for absolute beginners with no experience in programming. You will learn the key ideas behind deep learning without any code.',
                'category_id' => 4,
                'publish_date' => '2020-07-30',
                'url' => 'https://youtu.be/VyWAvY2CF9c?si=5BdtLxMg4pUNz18h',
            ],
            [
                'thumbnail' => 'Video47.jpg',
                'title' => 'How Deep Neural Networks Work - Full Course for Beginners',
                'creator' => 'freeCodeCamp.org',
                'description' => '
Neural networks are at the core of what we are calling Artificial Intelligence today. They can seem impenetrable, even mystical, if you are trying to understand them for the first time, but they don\'t have to.',
                'category_id' => 4,
                'publish_date' => '2019-04-16',
                'url' => 'https://youtu.be/dPWYUELwIdM?si=0P2S2p83F_w6rEkh',
            ],
            [
                'thumbnail' => 'Video48.jpg',
                'title' => 'TensorFlow 2.0 Complete Course - Python Neural Networks for Beginners Tutorial',
                'creator' => 'freeCodeCamp.org',
                'description' => 'Learn how to use TensorFlow 2.0 in this full tutorial course for beginners. This course is designed for Python programmers looking to enhance their knowledge and skills in machine learning and artificial intelligence. ',
                'category_id' => 4,
                'publish_date' => '2020-03-03',
                'url' => 'https://youtu.be/tPYj3fFJGjk?si=zxyPC-i-MgPMNWM6',
            ],
            [
                'thumbnail' => 'Video49.jpg',
                'title' => 'TensorFlow in 100 Seconds',
                'creator' => 'Fireship',
                'description' => 'TensorFlow is a tool for machine learning capable of building deep neural networks with high-level Python code. It provides developer-friendly APIs that help software engineers train, analyze, and deploy ML models. ',
                'category_id' => 4,
                'publish_date' => '2020-08-03',
                'url' => 'https://youtu.be/i8NETqtGHms?si=2h5Uv97hl_nhOAQ9',
            ],
            [
                'thumbnail' => 'Video50.jpg',
                'title' => 'Tensorflow Object Detection in 5 Hours with Python | Full Course with 3 Projects',
                'creator' => 'Nicholas Renotte',
                'description' => 'In this course, you\'ll learn everything you need to know to go from beginner to practitioner when it comes to deep learning object detection with Tensorflow. This course mainly revolves around Python but there\'s a little Javascript thrown in as well when it comes to building a web app in Project 2. But don\'t fret we\'ll take it step by step so you can take your time and work through it. All the code it made available through GitHub, links below.  ',
                'category_id' => 4,
                'publish_date' => '2021-04-09',
                'url' => 'https://youtu.be/yqkISICHH-U?si=ZJOq5Wp-oFPs6c4i',
            ],
            [
                'thumbnail' => 'Video51.jpg',
                'title' => 'PyTorch Tutorial 01 - Installation',
                'creator' => 'Patrick Loeber',
                'description' => 'I show you how I install PyTorch on my Mac using Anaconda. Installation on Linux or Windows can be done almost the same way.',
                'category_id' => 4,
                'publish_date' => '2019-12-14',
                'url' => 'https://youtu.be/EMXfZB8FVUA?si=8cNMBSRRZ4kYCBCh',
            ],
            [
                'thumbnail' => 'Video52.jpg',
                'title' => 'Large Language Models explained briefly',
                'creator' => '3Blue1Brown',
                'description' => '3blue1brown is a channel about animating math, in all senses of the word animate. If you\'re reading the bottom of a video description, I\'m guessing you\'re more interested than the average viewer in lessons here. It would mean a lot to me if you chose to stay up to date on new ones, either by subscribing here on YouTube or otherwise following on whichever platform below you check most regularly.',
                'category_id' => 4,
                'publish_date' => '2024-11-20',
                'url' => 'https://youtu.be/LPZh9BOjkQs?si=YrhoKX0gPpl6c-TM',
            ],
            [
                'thumbnail' => 'Video53.jpg',
                'title' => 'Transformers (how LLMs work) explained visually | DL5',
                'creator' => '3Blue1Brown',
                'description' => '3blue1brown is a channel about animating math, in all senses of the word animate. If you\'re reading the bottom of a video description, I\'m guessing you\'re more interested than the average viewer in lessons here. It would mean a lot to me if you chose to stay up to date on new ones, either by subscribing here on YouTube or otherwise following on whichever platform below you check most regularly.',
                'category_id' => 4,
                'publish_date' => '2024-04-02',
                'url' => 'https://youtu.be/wjZofJX0v4M?si=dv1NWZp0ZCcyJkGe',
            ],
            [
                'thumbnail' => 'Video54.jpg',
                'title' => 'But what is a neural network? | Deep learning chapter 1',
                'creator' => '3Blue1Brown',
                'description' => '3blue1brown is a channel about animating math, in all senses of the word animate. If you\'re reading the bottom of a video description, I\'m guessing you\'re more interested than the average viewer in lessons here. It would mean a lot to me if you chose to stay up to date on new ones, either by subscribing here on YouTube or otherwise following on whichever platform below you check most regularly.',
                'category_id' => 4,
                'publish_date' => '2017-10-05',
                'url' => 'https://youtu.be/aircAruvnKk?si=Gu83f6NCFcZ0mrMy',
            ],
            [
                'thumbnail' => 'Video55.jpg',
                'title' => 'Gradient descent, how neural networks learn | DL2',
                'creator' => '3Blue1Brown',
                'description' => '3blue1brown is a channel about animating math, in all senses of the word animate. If you\'re reading the bottom of a video description, I\'m guessing you\'re more interested than the average viewer in lessons here. It would mean a lot to me if you chose to stay up to date on new ones, either by subscribing here on YouTube or otherwise following on whichever platform below you check most regularly.',
                'category_id' => 4,
                'publish_date' => '2017-10-16',
                'url' => 'https://youtu.be/IHZwWFHWa-w?si=Sas9EChcuOcbr2O1',
            ],
            [
                'thumbnail' => 'Video56.jpg',
                'title' => 'Backpropagation, step-by-step | DL3',
                'creator' => '3Blue1Brown',
                'description' => '3blue1brown is a channel about animating math, in all senses of the word animate. If you\'re reading the bottom of a video description, I\'m guessing you\'re more interested than the average viewer in lessons here. It would mean a lot to me if you chose to stay up to date on new ones, either by subscribing here on YouTube or otherwise following on whichever platform below you check most regularly.',
                'category_id' => 4,
                'publish_date' => '2017-11-03',
                'url' => 'https://youtu.be/Ilg3gGewQ5U?si=wOp2kUiy-mWUtGsJ',
            ],
            [
                'thumbnail' => 'Video57.jpg',
                'title' => 'Backpropagation calculus | DL4',
                'creator' => '3Blue1Brown',
                'description' => '3blue1brown is a channel about animating math, in all senses of the word animate. If you\'re reading the bottom of a video description, I\'m guessing you\'re more interested than the average viewer in lessons here. It would mean a lot to me if you chose to stay up to date on new ones, either by subscribing here on YouTube or otherwise following on whichever platform below you check most regularly.',
                'category_id' => 4,
                'publish_date' => '2017-11-03',
                'url' => 'https://youtu.be/tIeHLnjs5U8?si=4Xx_8kZm_NT7k7_9',
            ],
            [
                'thumbnail' => 'Video58.jpg',
                'title' => 'Attention in transformers, visually explained | DL6',
                'creator' => '3Blue1Brown',
                'description' => '3blue1brown is a channel about animating math, in all senses of the word animate. If you\'re reading the bottom of a video description, I\'m guessing you\'re more interested than the average viewer in lessons here. It would mean a lot to me if you chose to stay up to date on new ones, either by subscribing here on YouTube or otherwise following on whichever platform below you check most regularly.',
                'category_id' => 4,
                'publish_date' => '2024-04-07',
                'url' => 'https://youtu.be/eMlx5fFNoYc?si=C82IkvqFN36ZD1Ze',
            ],
            [
                'thumbnail' => 'Video59.jpg',
                'title' => 'How might LLMs store facts | DL7',
                'creator' => '3Blue1Brown',
                'description' => '3blue1brown is a channel about animating math, in all senses of the word animate. If you\'re reading the bottom of a video description, I\'m guessing you\'re more interested than the average viewer in lessons here. It would mean a lot to me if you chose to stay up to date on new ones, either by subscribing here on YouTube or otherwise following on whichever platform below you check most regularly.',
                'category_id' => 4,
                'publish_date' => '2024-08-31',
                'url' => 'https://youtu.be/9-Jl0dxWQs8?si=mliOOxCax59MW7ik',
            ],
            [
                'thumbnail' => 'Video60.jpg',
                'title' => 'What are GANs (Generative Adversarial Networks)?',
                'creator' => 'IBM Technology',
                'description' => '3blue1brown is a channel about animating math, in all senses of the word animate. If you\'re reading the bottom of a video description, I\'m guessing you\'re more interested than the average viewer in lessons here. It would mean a lot to me if you chose to stay up to date on new ones, either by subscribing here on YouTube or otherwise following on whichever platform below you check most regularly.',
                'category_id' => 4,
                'publish_date' => '2021-11-11',
                'url' => 'https://youtu.be/TpMIssRdhco?si=ubKXaQXxvNwRYbwl',
            ],
        ];

        foreach($videos as $video) {
            $thumbnailSource = database_path('seeders/resources/Videos/Thumbnail/' . basename($video['thumbnail']));

            if (file_exists($thumbnailSource)) {
                Storage::disk('public')->put('Videos/Thumbnail/' . basename($video['thumbnail']), file_get_contents($thumbnailSource));
            }

            DB::table('videos')->insert([
                'thumbnail' => 'Videos/Thumbnail/' . basename($video['thumbnail']),
                'title' => $video['title'],
                'creator' => $video['creator'],
                'description' => $video['description'],
                'category_id' => $video['category_id'],
                'publish_date' => $video['publish_date'],
                'url' => $video['url'],
            ]);
        }
    }
}
